### ISSUE TITLE
Undefined Flags

### ISSUE THREAD

**Issue by christopher-swiftchain** [Parasrah/elm-react-component#52]
I get the following error when adding flags to the module:

`<Counter messageFlag="test" />`

`Unhandled Runtime Error
TypeError: Cannot read property 'messageFlag' of undefined`

This points to:

`        if (!app.ports[name] && !isFlagOnly) {
`

Any guidance to troubleshooting this would be appreciated.

**Comment by christopher-swiftchain** [comment]
This is a next.js project.

**Comment by Parasrah** [comment]
Hmm, it seems to me like perhaps the object being passed into `wrap` is malformed? Would you be able to change your code like so:

```
import wrap from '@elm-react/component'

import Counter from './Counter.elm'

console.log(Counter)

export default wrap(Counter)
```

to add a log for what you're passing into `wrap` and see what you get? And maybe post a screenshot here or something? Also are you using `Browser.element`?

**Comment by christopher-swiftchain** [comment]
Thank you @Parasrah , I am glad that you asked if I am using `Browser.element` because I'm not, I am using [elm-ui](https://package.elm-lang.org/packages/mdgriffith/elm-ui/latest/)

after considering your question about `Browser.element` I reverted all my work back to basic `Browser.element` and the ports and flags worked, as soon as I changed back to `Elm-ui` I get the `Unhandled Runtime Error TypeError: Cannot read property 'messageFlag' of undefined` Error.

The module I am using within my Elm is also written in `Elm-ui` so that's why I used `Elm-ui`.

**Comment by christopher-swiftchain** [comment]
@Parasrah I've managed to get it working with Elm-ui, knowing it could've been an issue helped, however, when I use the Counter example code and remove the references to the `onChange` and `value ports`, I get the same undefined error.

Am i Missing something?

I simply only need to pass in one flag called messageFlag.

This code works, but when I remove the increment ports i get `messageFlag of undefined`

`port module Counter exposing (..)

import Browser
import Html exposing (Html, button, div, span)
import Html.Attributes exposing (class)
import Html.Events exposing (onClick)
import Json.Decode as D exposing (Decoder)
import Json.Decode.Pipeline exposing (required)
import Json.Encode as E exposing (Value)

import Element exposing (Element, el, text, row, alignRight, fill, width, rgb255, spacing, centerY, padding)
import Element.Background as Background
import Element.Border as Border
import Element.Font as Font



-- Ports (interop with props)


port onChange : Int -> Cmd msg



-- Flags (initialization)


type alias Flags =
    { messageFlag : String
    }


flagsDecoder : Decoder Flags
flagsDecoder =
    D.succeed Flags
        |> required "messageFlag" D.string


defaultFlags : Flags
defaultFlags =
    { messageFlag = "failed to parse flags" }



-- Model


type alias Model =
    { message : String
    }


init : Value -> ( Model, Cmd Msg )
init flagsJson =
    let
        flags =
            D.decodeValue flagsDecoder flagsJson |> Result.withDefault defaultFlags
    in
    ( { message = flags.messageFlag
      }
    , Cmd.none
    )



-- Msg


type Msg
    = Increment
    | Decrement



-- Subscriptions


subscriptions : Model -> Sub Msg
subscriptions _ =
  Sub.none



-- Update


update : Msg -> Model -> ( Model, Cmd Msg )
update msg model =
    case msg of
        Increment ->
            ( model
            , onChange 1
            )

        Decrement ->
            ( model
            , onChange -1
            )


main : Program Value Model Msg
main =
    Browser.element
        { view = view
        , update = update
        , init = init
        , subscriptions = subscriptions
        }

view : Model -> Html msg
view model =
    Element.layout [] <|
        row []
        [ 
            el [ alignRight ] (text model.message)
        ]`

**Comment by Parasrah** [comment]
Ahh you're right, I know what the problem is. For now you're going to need to keep those ports around until I have time to release a fix

the issue is line 143:

```
if (!app.ports[name] && !isFlagOnly) {
```

I'd assumed ports would be an empty object if none were defined, but instead it is undefined. Need to fix that and verify I didn't make the same assumption elsewhere. Thanks for reporting, I'll try to get this taken care of as soon as I can
